# Basic
title: Fugang
subtitle: Committed to front-end and gis development.
welcome_message: <a href="https://github.com/sharealex" target="_blank"></a>
description: 时代的车轰轰地往前开。我们生存在车子上，经过的也许不过是几条熟悉的街道，可是漫天的火光中也自惊心动魄。就可惜我们只顾在一瞥即逝的店铺的橱窗里找寻我们自己的影子。我们只看见自己的脸，苍白，渺小，我们的自私与空虚，我们恬不知耻的愚蠢。谁都像我们一样，然而我们每个人都是孤独的。--张爱玲
creator: <a href="http://sharealex.top">@Fugang</a>

url: "http://sharealex.top"

permalink: /:year/:month/:title/

# Format
rouge: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Blog
# Navigation buttons in the front page.
nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
   # - {title: Another Button, description: A button, url: 'http://example.com'}
   # - {title: Content,        in_site: true,  description: content,                 url: '/timeline'}
     - {title: Cnblogs,       in_site: true,  description: Fugang's cnblogs,   url: 'http://www.cnblogs.com/sharealex'}
   # - {title: GitHub,     in_site: false,  description: icurious's GitHub,      url: 'https://github.com/sharealex'}
   # - {title: Devs,   in_site: true,  description: Friends,                  url: '/friends'}
     - {title: About,        in_site: true,  description: About the author liuqi,        url: '/about'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: fugang
    
# Social
social:
    weibo: fugang521
    github: sharealex

    copyright: http://www.cnblogs.com/sharealex

# Google Analytics
ga:
    id: UA-86995833-1
    host: sharealex.top
