# Basic
title: LiuQi-Dev
subtitle: Liuqi and his daily.
welcome_message: <a href="https://github.com/liuqidev" target="_blank"></a>
description: 夫天地者万物之逆旅也；光阴者百代之过客也。而浮生若梦，为欢几何？古人秉烛夜游，良有以也。况阳春召我以烟景，大块假我以文章。会桃花之芳园，序天伦之乐事。
creator: <a href="http://www.blankspace.cn">@liuqidev</a>

url: "http://www.blankspace.cn"

permalink: /:year/:month/:title/

# Format
rouge: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Blog
# Navigation buttons in the front page.
nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
   # - {title: Another Button, description: A button, url: 'http://example.com'}
   # - {title: Content,        in_site: true,  description: content,                 url: '/timeline'}
     - {title: CSDN,       in_site: false,  description: iCurious's CSDN blog,   url: 'http://blog.csdn.net/icurious'}
   # - {title: GitHub,     in_site: false,  description: icurious's GitHub,      url: 'https://github.com/liuqidev'}
   # - {title: Devs,   in_site: true,  description: Friends,                  url: '/friends'}
     - {title: About,        in_site: true,  description: About the author liuqi,        url: '/about'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: liuqidev
    # duoshuo: 
    
# Social
social:
    weibo: liuqidev
    github: liuqidev
  # twitter: 
    gplus: 112373242775367333102
    rss: /feed.xml
    mail: liuqi.dev@gmail.com
  # copyright: http://blog.csdn.net/icurious

# Google Analytics
ga:
    id: UA-86995833-1
    host: www.blankspace.cn
